language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python setup.py bdist_wheel sdist
deploy:
  provider: pypi
  user: __toke__
  password: 
    secure: Uh9c/WEctoq5LOyPK68xdrgUPpXAX0vSil5vszFAP3jd0QKJynmNV4Hccs3QPs00Fi/O0qvMKheJFemxy0BFV7RXHQDTE6ZFJMjqPcXYUDrS/BZaIegYcUEocN16ZZb6Ebc281KOTWGflNlUACZVvYbbmqY+ktLNw8cmPvdpUXxnjXzKRq7avyKFJVtdbR9ju/0wSNPZ70L9g1uSLh4BENrVGvJnZbYOgdOI9fPmztqVVO3SHstSIYMszriKaYcK7L+gm/eMX4Nk1mcz2Bjv0TTbhluJSjcr+Etg/IvwKyQb0J1xp+TsunGbexEXMqcgSLCb1oaO3cdiWaTQzEnjgmKT3c5KdX+IJ3bgnIbPPwT+7JjdAvc3NpzSluxrxZloRQg87NocLVroTZy9t2JgH39dLp3nJlPpbb3wUAJ3xArGXLiAN4fAIhYACtvS8UxgRtpdJR3rmrX+AY3UvJTrCKSKzekzWJQKSMKFFP+k1qjO0ARDmf5f6x+OetRKX5Ww2adJgdGT7ECg1ZqG9IF9ZG7uUPEpaurw1nHO0xWIeBicbxRAHBMSBknjVopSt4nMwPV6Ycq9esL5oOAqkqUzcUF9EM104eGL/BlITZavod20LbG7pYDhl65FfqQp6UrzwsyuQ6VEUg4fbCwknv/9Jl3YJZJMzhLMCjWUaRG2B3Q=  
  skip_cleanup: true
  on:
    tags: true
  skip_existing: true
  
