language: python
python:
- '3.6'
install:
- pip install .
script:
- python setup.py bdist_wheel sdist
deploy:
  provider: pypi
  user: __token__
  password: 
    secure: d08n601ZZ+ADFheWL9wkCTtWSDpUY8mH2jeIcAWzEKsaY4QBTBb7q/4jLwbRsLDBnKO4lOlm8sunV/pZbc/s5MZfRvlJ8rnDx6F+2TjGMJ9tFyaLo17pMM8t6kN4hHLGdmICRM7/IL9fN3+GVfRpBxBGjLbV+JtvvrWkFAYM37XaNwgbiVl4Hg0aI/iJNoK1EsM9RAXZYmeVAyGZ5IhI8eI7YYmwm5l37Qsk9hfGISZgHk7Nm3hdtIvqsSRQLvfW4dgMDk+CHMb/vQyKKRgZGzTMI7JMtYMgDfmB9N/qcIW3Df0Ja9/7h+Tl8vhTfpcWQp5lquQfpD7jdwh8YhIYSR1EpKB3cIVILE58aowBO1FayVMimoSCPPAKu5b4V/wFD+jqiWPOnN6TqeJC9lCHSNBgICwSur0O2pbCQf/R1eCg4LiXlkyRgpZ0QrGNcQyMLw0H9YlH4MuKc+yoUnNCkjgFLtbHmUw5PFiHXVSj2cWG9z2P+V19JetEpKDnmcga1drfEs9YWqUJ5HYOStp7HSQCNNJVIEn05KAvWubFH4PG4D0afdTdgF4g0puvFdEizKbm9HnMdMJjs7SdUPPsHq+6emELaDwhCKYlAxxI3sJqsPtavMwXENKdCYYAz48X1gwcTF019APIjrHKtW++qPCjq+H6t1q9N6mxK2JN2ic=
  skip_cleanup: true
  on:
    tags: true
  skip_existing: true
  
