language: python
python:
- '3.6'
install:
- pip install .
script:
- python setup.py bdist_wheel sdist
deploy:
  provider: pypi
  user: __token__
  password: 
    secure: pm7uihoxem/chmRAgRabAL0FkksGk3+/6resA0rGTEpWFsgap5QKIq/BHeoFhEUS0A6S0xAwzfwJkCqFbEk0DBGidbHWxn4mjAA1ZHgAR8lE/aaHuSRtZRd8MOGYHW70nfA6e4wsYBrIURtK/KgC0K5SVIQ7pVByXkSIqvXI1HrfsQcZdV0YDNK6UyCK4iVGca+V+ikP8NFG7fmD1JqJgKU/KVvFImJY5Z8RTsyzggl5ZDrJyRZrc7IpDGNgpavM8/aTmiRNOVYUkoKr8TUOPyRfxPbXsAdg2NXTIFiyEtgdE6tQ4E+jUOpfDIo31zfHzFXKgO/M2LGQe6YQ//g+5bFPRDb8alyckHsUaRnOBWMk2rpDbvNKzDBnshoqRJjRx0Szuy1dLfDGL6PkBxkGgABw2p6PnND06zG5TSagWjKpw7GbCQMXXVbqe/g1DEEx/JafmDZ852OgMy2oMBESQpjXxUGaKx+V40YrqLIKig46ld08D7e0pB24eTJpYP0LJmUjrXzupEWAwgghtA+B9p88xUkVLaha0ll1RRnA5oDSUyHi+cKjzZkiPcy3/9SuNvrvZbfA1nm6t1LZF9PWlj6eYX0f8cDPOGyrNIpTy8Ip17a6XTzVML0GvCHFY4wgETzrT7v47thkKXU1wFelhUS2XWk6/10niEyKDBarYeI=
  skip_cleanup: true
  on:
    tags: false
  skip_existing: true
  
